/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/haY9MKKZqpX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";

export function Campaign() {
  return (
    <Card className="w-full max-w-4xl">
      <CardHeader>
        <CardTitle>Create/Edit Campaign</CardTitle>
        <CardDescription>
          Fill out the details for your D&D campaign.
        </CardDescription>
      </CardHeader>
      <CardContent className="grid gap-6">
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div className="space-y-2">
            <Label htmlFor="title">Title</Label>
            <Input id="title" placeholder="Enter campaign title" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="turn-frequency">Turn Frequency</Label>
            <Select name="turn-frequency">
              <SelectTrigger>
                <SelectValue placeholder="Select frequency" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="hourly">Hourly</SelectItem>
                <SelectItem value="daily">Daily</SelectItem>
                <SelectItem value="weekly">Weekly</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="world-setting">World Setting</Label>
          <Textarea
            id="world-setting"
            placeholder="Describe the world setting"
            rows={5}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="adventure-details">Adventure Details</Label>
          <Textarea
            id="adventure-details"
            placeholder="Describe the adventure details"
            rows={5}
          />
        </div>
        <Separator />
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div className="space-y-2">
            <Label htmlFor="invite-email">Invite by Email</Label>
            <Textarea
              id="invite-email"
              placeholder="Enter email addresses separated by commas"
              rows={3}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="invite-phone">Invite by Phone</Label>
            <Textarea
              id="invite-phone"
              placeholder="Enter phone numbers separated by commas"
              rows={3}
            />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="invite-user-id">Invite by User ID</Label>
          <Textarea
            id="invite-user-id"
            placeholder="Enter user IDs separated by commas"
            rows={3}
          />
        </div>
        <Separator />
        <div className="grid gap-4">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-medium">Player Applications</h3>
            <Button size="sm" variant="outline">
              View All
            </Button>
          </div>
          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage alt="Player 1" src="/avatars/01.png" />
                  <AvatarFallback>P1</AvatarFallback>
                </Avatar>
                <div>
                  <p className="font-medium">Player 1</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    player1@example.com
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Badge
                  className="bg-green-100 text-green-600 dark:bg-green-900 dark:text-green-200"
                  variant="outline"
                >
                  Accepted
                </Badge>
                <Button size="sm" variant="ghost">
                  <ChevronRightIcon className="h-4 w-4" />
                </Button>
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage alt="Player 2" src="/avatars/02.png" />
                  <AvatarFallback>P2</AvatarFallback>
                </Avatar>
                <div>
                  <p className="font-medium">Player 2</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    player2@example.com
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Badge
                  className="bg-yellow-100 text-yellow-600 dark:bg-yellow-900 dark:text-yellow-200"
                  variant="outline"
                >
                  Pending
                </Badge>
                <Button size="sm" variant="ghost">
                  <ChevronRightIcon className="h-4 w-4" />
                </Button>
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Avatar>
                  <AvatarImage alt="Player 3" src="/avatars/03.png" />
                  <AvatarFallback>P3</AvatarFallback>
                </Avatar>
                <div>
                  <p className="font-medium">Player 3</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    player3@example.com
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Badge
                  className="bg-red-100 text-red-600 dark:bg-red-900 dark:text-red-200"
                  variant="outline"
                >
                  Rejected
                </Badge>
                <Button size="sm" variant="ghost">
                  <ChevronRightIcon className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
      <CardFooter className="flex justify-end gap-2">
        <Button variant="outline">Cancel</Button>
        <Button>Save Campaign</Button>
      </CardFooter>
    </Card>
  );
}

function ChevronRightIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}
